//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace Sunp.Api.Client {
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SunpApiClient {
        private string _baseUrl = "http://sunp-api.qoldau.kz";
        private System.Net.Http.HttpClient _httpClient;
        private System.Lazy<Newtonsoft.Json.JsonSerializerSettings> _settings;

        public SunpApiClient(string baseUrl, System.Net.Http.HttpClient httpClient) {
            _baseUrl = baseUrl;
            _httpClient = httpClient;
            _settings = new System.Lazy<Newtonsoft.Json.JsonSerializerSettings>(CreateSerializerSettings);
        }

        private Newtonsoft.Json.JsonSerializerSettings CreateSerializerSettings() {
            var settings = new Newtonsoft.Json.JsonSerializerSettings();
            UpdateJsonSerializerSettings(settings);
            return settings;
        }

        public string BaseUrl {
            get { return _baseUrl; }
            set { _baseUrl = value; }
        }

        protected Newtonsoft.Json.JsonSerializerSettings JsonSerializerSettings { get { return _settings.Value; } }

        partial void UpdateJsonSerializerSettings(Newtonsoft.Json.JsonSerializerSettings settings);

        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, string url);
        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
        partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response);

        /// <summary>
        /// Отправка замеров с массовых расходомеров на приеме
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<ResponseBodyBase> DeviceSendFlowmeterIndicatorsAsync(SendFlowmeterIndicatorsRequestBody requestBody) {
            return DeviceSendFlowmeterIndicatorsAsync(requestBody, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Отправка замеров с массовых расходомеров на приеме
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<ResponseBodyBase> DeviceSendFlowmeterIndicatorsAsync(SendFlowmeterIndicatorsRequestBody requestBody, System.Threading.CancellationToken cancellationToken) {
            if (requestBody == null)
                throw new System.ArgumentNullException("requestBody");

            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/Device/SendFlowmeterIndicators");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try {
                using (var request_ = new System.Net.Http.HttpRequestMessage()) {
                    var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(requestBody, _settings.Value);
                    var content_ = new System.Net.Http.StringContent(json_);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null) {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200) {
                            var objectResponse_ = await ReadObjectResponseAsync<ResponseBodyBase>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null) {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        } else {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    } finally {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            } finally {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Отправка замеров с электронных весов
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<ResponseBodyBase> ElectronicScaleSendElectronicScaleDataAsync(SendElectronicScaleRequestBody requestBody) {
            return ElectronicScaleSendElectronicScaleDataAsync(requestBody, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Отправка замеров с электронных весов
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<ResponseBodyBase> ElectronicScaleSendElectronicScaleDataAsync(SendElectronicScaleRequestBody requestBody, System.Threading.CancellationToken cancellationToken) {
            if (requestBody == null)
                throw new System.ArgumentNullException("requestBody");

            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/ElectronicScale/SendElectronicScaleData");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try {
                using (var request_ = new System.Net.Http.HttpRequestMessage()) {
                    var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(requestBody, _settings.Value);
                    var content_ = new System.Net.Http.StringContent(json_);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null) {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200) {
                            var objectResponse_ = await ReadObjectResponseAsync<ResponseBodyBase>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null) {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        } else {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    } finally {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            } finally {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Получение данных по заявителю
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<GetApplicantDataResponseBody> ProviderGetApplicantDataAsync(RequestBodyBase requestBody) {
            return ProviderGetApplicantDataAsync(requestBody, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Получение данных по заявителю
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<GetApplicantDataResponseBody> ProviderGetApplicantDataAsync(RequestBodyBase requestBody, System.Threading.CancellationToken cancellationToken) {
            if (requestBody == null)
                throw new System.ArgumentNullException("requestBody");

            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/Provider/GetApplicantData");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try {
                using (var request_ = new System.Net.Http.HttpRequestMessage()) {
                    var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(requestBody, _settings.Value);
                    var content_ = new System.Net.Http.StringContent(json_);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null) {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200) {
                            var objectResponse_ = await ReadObjectResponseAsync<GetApplicantDataResponseBody>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null) {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        } else {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    } finally {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            } finally {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Получение статуса обработки пакета данных
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<GetPackageStatusResponseBody> ProviderGetPackageStatusAsync(PackageRequestBody requestBody) {
            return ProviderGetPackageStatusAsync(requestBody, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Получение статуса обработки пакета данных
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<GetPackageStatusResponseBody> ProviderGetPackageStatusAsync(PackageRequestBody requestBody, System.Threading.CancellationToken cancellationToken) {
            if (requestBody == null)
                throw new System.ArgumentNullException("requestBody");

            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/Provider/GetPackageStatus");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try {
                using (var request_ = new System.Net.Http.HttpRequestMessage()) {
                    var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(requestBody, _settings.Value);
                    var content_ = new System.Net.Http.StringContent(json_);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null) {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200) {
                            var objectResponse_ = await ReadObjectResponseAsync<GetPackageStatusResponseBody>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null) {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        } else {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    } finally {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            } finally {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Получение статусов обработки пакетов данных
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<GetPackagesStatusResponseBody> ProviderGetPackagesStatusAsync(PackagesRequestBody requestBody) {
            return ProviderGetPackagesStatusAsync(requestBody, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Получение статусов обработки пакетов данных
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<GetPackagesStatusResponseBody> ProviderGetPackagesStatusAsync(PackagesRequestBody requestBody, System.Threading.CancellationToken cancellationToken) {
            if (requestBody == null)
                throw new System.ArgumentNullException("requestBody");

            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/Provider/GetPackagesStatus");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try {
                using (var request_ = new System.Net.Http.HttpRequestMessage()) {
                    var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(requestBody, _settings.Value);
                    var content_ = new System.Net.Http.StringContent(json_);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null) {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200) {
                            var objectResponse_ = await ReadObjectResponseAsync<GetPackagesStatusResponseBody>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null) {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        } else {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    } finally {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            } finally {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<System.Collections.Generic.ICollection<RefItem>> ReferenceGetOilProductTypeReferenceAsync() {
            return ReferenceGetOilProductTypeReferenceAsync(System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<System.Collections.Generic.ICollection<RefItem>> ReferenceGetOilProductTypeReferenceAsync(System.Threading.CancellationToken cancellationToken) {
            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/Reference/GetOilProductTypeReference");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try {
                using (var request_ = new System.Net.Http.HttpRequestMessage()) {
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null) {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200) {
                            var objectResponse_ = await ReadObjectResponseAsync<System.Collections.Generic.ICollection<RefItem>>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null) {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        } else {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    } finally {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            } finally {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Отправка замеров с резервуаров (хранение)
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<ResponseBodyBase> TankSendTankIndicatorsAsync(SendTankIndicatorsRequestBody requestBody) {
            return TankSendTankIndicatorsAsync(requestBody, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Отправка замеров с резервуаров (хранение)
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<ResponseBodyBase> TankSendTankIndicatorsAsync(SendTankIndicatorsRequestBody requestBody, System.Threading.CancellationToken cancellationToken) {
            if (requestBody == null)
                throw new System.ArgumentNullException("requestBody");

            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/Tank/SendTankIndicators");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try {
                using (var request_ = new System.Net.Http.HttpRequestMessage()) {
                    var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(requestBody, _settings.Value);
                    var content_ = new System.Net.Http.StringContent(json_);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null) {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200) {
                            var objectResponse_ = await ReadObjectResponseAsync<ResponseBodyBase>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null) {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        } else {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    } finally {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            } finally {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <summary>
        /// Отправка замеров с резервуаров (поставка)
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual System.Threading.Tasks.Task<ResponseBodyBase> TankSendTankTransfersAsync(SendTankTransfersRequestBody requestBody) {
            return TankSendTankTransfersAsync(requestBody, System.Threading.CancellationToken.None);
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Отправка замеров с резервуаров (поставка)
        /// </summary>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<ResponseBodyBase> TankSendTankTransfersAsync(SendTankTransfersRequestBody requestBody, System.Threading.CancellationToken cancellationToken) {
            if (requestBody == null)
                throw new System.ArgumentNullException("requestBody");

            var urlBuilder_ = new System.Text.StringBuilder();
            urlBuilder_.Append(BaseUrl != null ? BaseUrl.TrimEnd('/') : "").Append("/Tank/SendTankTransfers");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try {
                using (var request_ = new System.Net.Http.HttpRequestMessage()) {
                    var json_ = Newtonsoft.Json.JsonConvert.SerializeObject(requestBody, _settings.Value);
                    var content_ = new System.Net.Http.StringContent(json_);
                    content_.Headers.ContentType = System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json");
                    request_.Content = content_;
                    request_.Method = new System.Net.Http.HttpMethod("POST");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try {
                        var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
                        if (response_.Content != null && response_.Content.Headers != null) {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200) {
                            var objectResponse_ = await ReadObjectResponseAsync<ResponseBodyBase>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null) {
                                throw new ApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        } else {
                            var responseData_ = response_.Content == null ? null : await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
                            throw new ApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    } finally {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            } finally {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        protected struct ObjectResponseResult<T> {
            public ObjectResponseResult(T responseObject, string responseText) {
                this.Object = responseObject;
                this.Text = responseText;
            }

            public T Object { get; }

            public string Text { get; }
        }

        public bool ReadResponseAsString { get; set; }

        protected virtual async System.Threading.Tasks.Task<ObjectResponseResult<T>> ReadObjectResponseAsync<T>(System.Net.Http.HttpResponseMessage response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Threading.CancellationToken cancellationToken) {
            if (response == null || response.Content == null) {
                return new ObjectResponseResult<T>(default(T), string.Empty);
            }

            if (ReadResponseAsString) {
                var responseText = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
                try {
                    var typedBody = Newtonsoft.Json.JsonConvert.DeserializeObject<T>(responseText, JsonSerializerSettings);
                    return new ObjectResponseResult<T>(typedBody, responseText);
                } catch (Newtonsoft.Json.JsonException exception) {
                    var message = "Could not deserialize the response body string as " + typeof(T).FullName + ".";
                    throw new ApiException(message, (int)response.StatusCode, responseText, headers, exception);
                }
            } else {
                try {
                    using (var responseStream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false))
                    using (var streamReader = new System.IO.StreamReader(responseStream))
                    using (var jsonTextReader = new Newtonsoft.Json.JsonTextReader(streamReader)) {
                        var serializer = Newtonsoft.Json.JsonSerializer.Create(JsonSerializerSettings);
                        var typedBody = serializer.Deserialize<T>(jsonTextReader);
                        return new ObjectResponseResult<T>(typedBody, string.Empty);
                    }
                } catch (Newtonsoft.Json.JsonException exception) {
                    var message = "Could not deserialize the response body stream as " + typeof(T).FullName + ".";
                    throw new ApiException(message, (int)response.StatusCode, string.Empty, headers, exception);
                }
            }
        }

        private string ConvertToString(object value, System.Globalization.CultureInfo cultureInfo) {
            if (value == null) {
                return "";
            }

            if (value is System.Enum) {
                var name = System.Enum.GetName(value.GetType(), value);
                if (name != null) {
                    var field = System.Reflection.IntrospectionExtensions.GetTypeInfo(value.GetType()).GetDeclaredField(name);
                    if (field != null) {
                        var attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(field, typeof(System.Runtime.Serialization.EnumMemberAttribute))
                            as System.Runtime.Serialization.EnumMemberAttribute;
                        if (attribute != null) {
                            return attribute.Value != null ? attribute.Value : name;
                        }
                    }

                    var converted = System.Convert.ToString(System.Convert.ChangeType(value, System.Enum.GetUnderlyingType(value.GetType()), cultureInfo));
                    return converted == null ? string.Empty : converted;
                }
            } else if (value is bool) {
                return System.Convert.ToString((bool)value, cultureInfo).ToLowerInvariant();
            } else if (value is byte[]) {
                return System.Convert.ToBase64String((byte[])value);
            } else if (value.GetType().IsArray) {
                var array = System.Linq.Enumerable.OfType<object>((System.Array)value);
                return string.Join(",", System.Linq.Enumerable.Select(array, o => ConvertToString(o, cultureInfo)));
            }

            var result = System.Convert.ToString(value, cultureInfo);
            return result == null ? "" : result;
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateEntityResponseBody : ResponseBodyBase {
        [Newtonsoft.Json.JsonProperty("entityId", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public long? EntityId { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ResponseBodyBase {
        [Newtonsoft.Json.JsonProperty("success", Required = Newtonsoft.Json.Required.Always)]
        public bool Success { get; set; }

        [Newtonsoft.Json.JsonProperty("error", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Error { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateApplicantRequestBody : RequestBodyBase {
        [Newtonsoft.Json.JsonProperty("bin", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Bin { get; set; }

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class RequestBodyBase {
        [Newtonsoft.Json.JsonProperty("requestGuid", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"\b[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}\b")]
        public string RequestGuid { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateObjectRequestBody : RequestBodyBase {
        [Newtonsoft.Json.JsonProperty("applicantId", Required = Newtonsoft.Json.Required.Always)]
        public long ApplicantId { get; set; }

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; }

        [Newtonsoft.Json.JsonProperty("objectType", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ObjectsType ObjectType { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum ObjectsType {

        [System.Runtime.Serialization.EnumMember(Value = @"PetrolStation")]
        PetrolStation = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Refinery")]
        Refinery = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"RefineryLow")]
        RefineryLow = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"OilBase")]
        OilBase = 3,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateTankRequestBody : RequestBodyBase {
        [Newtonsoft.Json.JsonProperty("objectId", Required = Newtonsoft.Json.Required.Always)]
        public long ObjectId { get; set; }

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string Name { get; set; }

        [Newtonsoft.Json.JsonProperty("oilProductType", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public OilProductType OilProductType { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum OilProductType {

        [System.Runtime.Serialization.EnumMember(Value = @"AI76")]
        AI76 = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"AI80")]
        AI80 = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"AI80K2")]
        AI80K2 = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"AI80K3")]
        AI80K3 = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"AI80K4")]
        AI80K4 = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"AI80K5")]
        AI80K5 = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"AI91")]
        AI91 = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"AI91K2")]
        AI91K2 = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"AI91K3")]
        AI91K3 = 8,

        [System.Runtime.Serialization.EnumMember(Value = @"AI91K4")]
        AI91K4 = 9,

        [System.Runtime.Serialization.EnumMember(Value = @"AI91K5")]
        AI91K5 = 10,

        [System.Runtime.Serialization.EnumMember(Value = @"AI92")]
        AI92 = 11,

        [System.Runtime.Serialization.EnumMember(Value = @"AI92K2")]
        AI92K2 = 12,

        [System.Runtime.Serialization.EnumMember(Value = @"AI92K3")]
        AI92K3 = 13,

        [System.Runtime.Serialization.EnumMember(Value = @"AI92K4")]
        AI92K4 = 14,

        [System.Runtime.Serialization.EnumMember(Value = @"AI92K5")]
        AI92K5 = 15,

        [System.Runtime.Serialization.EnumMember(Value = @"AI92PRIME")]
        AI92PRIME = 16,

        [System.Runtime.Serialization.EnumMember(Value = @"AI93")]
        AI93 = 17,

        [System.Runtime.Serialization.EnumMember(Value = @"AI93K2")]
        AI93K2 = 18,

        [System.Runtime.Serialization.EnumMember(Value = @"AI93K3")]
        AI93K3 = 19,

        [System.Runtime.Serialization.EnumMember(Value = @"AI93K4")]
        AI93K4 = 20,

        [System.Runtime.Serialization.EnumMember(Value = @"AI93K5")]
        AI93K5 = 21,

        [System.Runtime.Serialization.EnumMember(Value = @"AI95")]
        AI95 = 22,

        [System.Runtime.Serialization.EnumMember(Value = @"AI95K2")]
        AI95K2 = 23,

        [System.Runtime.Serialization.EnumMember(Value = @"AI95K3")]
        AI95K3 = 24,

        [System.Runtime.Serialization.EnumMember(Value = @"AI95K4")]
        AI95K4 = 25,

        [System.Runtime.Serialization.EnumMember(Value = @"AI95K5")]
        AI95K5 = 26,

        [System.Runtime.Serialization.EnumMember(Value = @"AI95PREMIUM")]
        AI95PREMIUM = 27,

        [System.Runtime.Serialization.EnumMember(Value = @"AI95PRIME")]
        AI95PRIME = 28,

        [System.Runtime.Serialization.EnumMember(Value = @"G95")]
        G95 = 29,

        [System.Runtime.Serialization.EnumMember(Value = @"AI96")]
        AI96 = 30,

        [System.Runtime.Serialization.EnumMember(Value = @"AI96K2")]
        AI96K2 = 31,

        [System.Runtime.Serialization.EnumMember(Value = @"AI96K3")]
        AI96K3 = 32,

        [System.Runtime.Serialization.EnumMember(Value = @"AI96K4")]
        AI96K4 = 33,

        [System.Runtime.Serialization.EnumMember(Value = @"AI96K5")]
        AI96K5 = 34,

        [System.Runtime.Serialization.EnumMember(Value = @"AI98")]
        AI98 = 35,

        [System.Runtime.Serialization.EnumMember(Value = @"AI98K2")]
        AI98K2 = 36,

        [System.Runtime.Serialization.EnumMember(Value = @"AI98K3")]
        AI98K3 = 37,

        [System.Runtime.Serialization.EnumMember(Value = @"AI98K4")]
        AI98K4 = 38,

        [System.Runtime.Serialization.EnumMember(Value = @"AI98K5")]
        AI98K5 = 39,

        [System.Runtime.Serialization.EnumMember(Value = @"AI98SUPER")]
        AI98SUPER = 40,

        [System.Runtime.Serialization.EnumMember(Value = @"AI98PRIME")]
        AI98PRIME = 41,

        [System.Runtime.Serialization.EnumMember(Value = @"AI100")]
        AI100 = 42,

        [System.Runtime.Serialization.EnumMember(Value = @"G100")]
        G100 = 43,

        [System.Runtime.Serialization.EnumMember(Value = @"DT")]
        DT = 44,

        [System.Runtime.Serialization.EnumMember(Value = @"DTZ")]
        DTZ = 45,

        [System.Runtime.Serialization.EnumMember(Value = @"DTZK2")]
        DTZK2 = 46,

        [System.Runtime.Serialization.EnumMember(Value = @"DTZK3")]
        DTZK3 = 47,

        [System.Runtime.Serialization.EnumMember(Value = @"DTZK4")]
        DTZK4 = 48,

        [System.Runtime.Serialization.EnumMember(Value = @"DTZK5")]
        DTZK5 = 49,

        [System.Runtime.Serialization.EnumMember(Value = @"DTZPRIME")]
        DTZPRIME = 50,

        [System.Runtime.Serialization.EnumMember(Value = @"DTL")]
        DTL = 51,

        [System.Runtime.Serialization.EnumMember(Value = @"DTLK2")]
        DTLK2 = 52,

        [System.Runtime.Serialization.EnumMember(Value = @"DTLK3")]
        DTLK3 = 53,

        [System.Runtime.Serialization.EnumMember(Value = @"DTLK4")]
        DTLK4 = 54,

        [System.Runtime.Serialization.EnumMember(Value = @"DTLK5")]
        DTLK5 = 55,

        [System.Runtime.Serialization.EnumMember(Value = @"DTLPRIME")]
        DTLPRIME = 56,

        [System.Runtime.Serialization.EnumMember(Value = @"DTA")]
        DTA = 57,

        [System.Runtime.Serialization.EnumMember(Value = @"DTAK2")]
        DTAK2 = 58,

        [System.Runtime.Serialization.EnumMember(Value = @"DTAK3")]
        DTAK3 = 59,

        [System.Runtime.Serialization.EnumMember(Value = @"DTAK4")]
        DTAK4 = 60,

        [System.Runtime.Serialization.EnumMember(Value = @"DTAK5")]
        DTAK5 = 61,

        [System.Runtime.Serialization.EnumMember(Value = @"DTE")]
        DTE = 62,

        [System.Runtime.Serialization.EnumMember(Value = @"DTEK2")]
        DTEK2 = 63,

        [System.Runtime.Serialization.EnumMember(Value = @"DTEK3")]
        DTEK3 = 64,

        [System.Runtime.Serialization.EnumMember(Value = @"DTEK4")]
        DTEK4 = 65,

        [System.Runtime.Serialization.EnumMember(Value = @"DTEK5")]
        DTEK5 = 66,

        [System.Runtime.Serialization.EnumMember(Value = @"DTXP")]
        DTXP = 67,

        [System.Runtime.Serialization.EnumMember(Value = @"DTM")]
        DTM = 68,

        [System.Runtime.Serialization.EnumMember(Value = @"M100")]
        M100 = 69,

        [System.Runtime.Serialization.EnumMember(Value = @"ZM40")]
        ZM40 = 70,

        [System.Runtime.Serialization.EnumMember(Value = @"ZM100")]
        ZM100 = 71,

        [System.Runtime.Serialization.EnumMember(Value = @"TS1")]
        TS1 = 72,

        [System.Runtime.Serialization.EnumMember(Value = @"JETFUEL")]
        JETFUEL = 73,

        [System.Runtime.Serialization.EnumMember(Value = @"PTB")]
        PTB = 74,

        [System.Runtime.Serialization.EnumMember(Value = @"HYDRAZINE")]
        HYDRAZINE = 75,

        [System.Runtime.Serialization.EnumMember(Value = @"NPD")]
        NPD = 76,

        [System.Runtime.Serialization.EnumMember(Value = @"DISTILLYAT")]
        DISTILLYAT = 77,

        [System.Runtime.Serialization.EnumMember(Value = @"UNKNOWN")]
        UNKNOWN = 78,

        [System.Runtime.Serialization.EnumMember(Value = @"NEFRAS")]
        NEFRAS = 79,

        [System.Runtime.Serialization.EnumMember(Value = @"KotToplivo")]
        KotToplivo = 80,

        [System.Runtime.Serialization.EnumMember(Value = @"KomponentVisokooktanBenz")]
        KomponentVisokooktanBenz = 81,

        [System.Runtime.Serialization.EnumMember(Value = @"Riformat")]
        Riformat = 82,

        [System.Runtime.Serialization.EnumMember(Value = @"BazaRT")]
        BazaRT = 83,

        [System.Runtime.Serialization.EnumMember(Value = @"LegkiGazoilKrekinga")]
        LegkiGazoilKrekinga = 84,

        [System.Runtime.Serialization.EnumMember(Value = @"StKatalizat")]
        StKatalizat = 85,

        [System.Runtime.Serialization.EnumMember(Value = @"GOBenzKK")]
        GOBenzKK = 86,

        [System.Runtime.Serialization.EnumMember(Value = @"NaftaKrekinga")]
        NaftaKrekinga = 87,

        [System.Runtime.Serialization.EnumMember(Value = @"Fr180_350")]
        Fr180_350 = 88,

        [System.Runtime.Serialization.EnumMember(Value = @"Fr60_250")]
        Fr60_250 = 89,

        [System.Runtime.Serialization.EnumMember(Value = @"KomponentAI92StKat")]
        KomponentAI92StKat = 90,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CreateDeviceRequestBody : RequestBodyBase {
        [Newtonsoft.Json.JsonProperty("objectId", Required = Newtonsoft.Json.Required.Always)]
        public long ObjectId { get; set; }

        [Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Name { get; set; }

        [Newtonsoft.Json.JsonProperty("deviceType", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public DeviceType DeviceType { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum DeviceType {

        [System.Runtime.Serialization.EnumMember(Value = @"Undefined")]
        Undefined = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"FlowmeterOutputAvto")]
        FlowmeterOutputAvto = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"FlowmeterOutputZhd")]
        FlowmeterOutputZhd = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"FlowmeterOutputTube")]
        FlowmeterOutputTube = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"FlowmeterInputAvto")]
        FlowmeterInputAvto = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"FlowmeterInputZhd")]
        FlowmeterInputZhd = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"FlowmeterInputTube")]
        FlowmeterInputTube = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"ElectronicScale")]
        ElectronicScale = 7,

        [System.Runtime.Serialization.EnumMember(Value = @"Transfer")]
        Transfer = 8,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GenerateTokenResponseBody : ResponseBodyBase {
        [Newtonsoft.Json.JsonProperty("token", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string Token { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GenerateTokenRequest : RequestBodyBase {
        [Newtonsoft.Json.JsonProperty("applicantBin", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public string ApplicantBin { get; set; }

        [Newtonsoft.Json.JsonProperty("applicantId", Required = Newtonsoft.Json.Required.Always)]
        public long ApplicantId { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SendFlowmeterIndicatorsRequestBody : PackageRequestBody {
        [Newtonsoft.Json.JsonProperty("flowmetersMeasurements", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.ICollection<FlowmeterMeasurements> FlowmetersMeasurements { get; set; } = new System.Collections.ObjectModel.Collection<FlowmeterMeasurements>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FlowmeterMeasurements {
        [Newtonsoft.Json.JsonProperty("flowmeterId", Required = Newtonsoft.Json.Required.Always)]
        public long FlowmeterId { get; set; }

        [Newtonsoft.Json.JsonProperty("measurements", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<FlowmeterMeasurementData> Measurements { get; set; } = new System.Collections.ObjectModel.Collection<FlowmeterMeasurementData>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class FlowmeterMeasurementData {
        [Newtonsoft.Json.JsonProperty("measurementDate", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTime MeasurementDate { get; set; }

        [Newtonsoft.Json.JsonProperty("totalMass", Required = Newtonsoft.Json.Required.Always)]
        public decimal TotalMass { get; set; }

        [Newtonsoft.Json.JsonProperty("flowMass", Required = Newtonsoft.Json.Required.Always)]
        public decimal FlowMass { get; set; }

        [Newtonsoft.Json.JsonProperty("massUnitType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public MassUnitType? MassUnitType { get; set; }

        [Newtonsoft.Json.JsonProperty("totalVolume", Required = Newtonsoft.Json.Required.Always)]
        public decimal TotalVolume { get; set; }

        [Newtonsoft.Json.JsonProperty("volumeUnitType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public VolumeUnitType? VolumeUnitType { get; set; }

        [Newtonsoft.Json.JsonProperty("currentDensity", Required = Newtonsoft.Json.Required.Always)]
        public decimal CurrentDensity { get; set; }

        [Newtonsoft.Json.JsonProperty("currentTemperature", Required = Newtonsoft.Json.Required.Always)]
        public decimal CurrentTemperature { get; set; }

        [Newtonsoft.Json.JsonProperty("oilProductType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public OilProductType? OilProductType { get; set; }

        [Newtonsoft.Json.JsonProperty("operationType", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public FlowmeterOperationType OperationType { get; set; }

        [Newtonsoft.Json.JsonProperty("sourceTankId", Required = Newtonsoft.Json.Required.Always)]
        public long SourceTankId { get; set; }

        [Newtonsoft.Json.JsonProperty("renterXin", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RenterXin { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum MassUnitType {

        [System.Runtime.Serialization.EnumMember(Value = @"Kilogram")]
        Kilogram = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Quintal")]
        Quintal = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"Ton")]
        Ton = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum VolumeUnitType {

        [System.Runtime.Serialization.EnumMember(Value = @"CubicMeter")]
        CubicMeter = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"CubicCentimeter")]
        CubicCentimeter = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"CubicDecimeter")]
        CubicDecimeter = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum FlowmeterOperationType {

        [System.Runtime.Serialization.EnumMember(Value = @"Undefined")]
        Undefined = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Filling")]
        Filling = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"FillingRenter")]
        FillingRenter = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"RefundDefective")]
        RefundDefective = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"Refund")]
        Refund = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"InternalDisplacement")]
        InternalDisplacement = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"Incoming")]
        Incoming = 6,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PackageRequestBody : RequestBodyBase {
        [Newtonsoft.Json.JsonProperty("packageId", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.RegularExpression(@"\b[A-Fa-f0-9]{8}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{4}-[A-Fa-f0-9]{12}\b")]
        public string PackageId { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SendElectronicScaleRequestBody : PackageRequestBody {
        [Newtonsoft.Json.JsonProperty("electronicScaleDatas", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.ICollection<ElectronicScaleDatas> ElectronicScaleDatas { get; set; } = new System.Collections.ObjectModel.Collection<ElectronicScaleDatas>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ElectronicScaleDatas {
        [Newtonsoft.Json.JsonProperty("objectId", Required = Newtonsoft.Json.Required.Always)]
        public long ObjectId { get; set; }

        [Newtonsoft.Json.JsonProperty("measurements", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<ElectronicScaleData> Measurements { get; set; } = new System.Collections.ObjectModel.Collection<ElectronicScaleData>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ElectronicScaleData {
        [Newtonsoft.Json.JsonProperty("cisternNumber", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string CisternNumber { get; set; }

        [Newtonsoft.Json.JsonProperty("routeNumber", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string RouteNumber { get; set; }

        [Newtonsoft.Json.JsonProperty("massEmpty", Required = Newtonsoft.Json.Required.Always)]
        public decimal MassEmpty { get; set; }

        [Newtonsoft.Json.JsonProperty("measurementDateTimeEmpty", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTime MeasurementDateTimeEmpty { get; set; }

        [Newtonsoft.Json.JsonProperty("massFull", Required = Newtonsoft.Json.Required.Always)]
        public decimal MassFull { get; set; }

        [Newtonsoft.Json.JsonProperty("measurementDateTimeFull", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTime MeasurementDateTimeFull { get; set; }

        [Newtonsoft.Json.JsonProperty("massDifference", Required = Newtonsoft.Json.Required.Always)]
        public decimal MassDifference { get; set; }

        [Newtonsoft.Json.JsonProperty("massUnitType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public MassUnitType? MassUnitType { get; set; }

        [Newtonsoft.Json.JsonProperty("oilProductType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public OilProductType? OilProductType { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetApplicantDataResponseBody : ResponseBodyBase {
        [Newtonsoft.Json.JsonProperty("applicantData", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public CollectedApplicantData ApplicantData { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CollectedApplicantData {
        [Newtonsoft.Json.JsonProperty("applicantId", Required = Newtonsoft.Json.Required.Always)]
        public long ApplicantId { get; set; }

        [Newtonsoft.Json.JsonProperty("applicantBin", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ApplicantBin { get; set; }

        [Newtonsoft.Json.JsonProperty("objects", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<CollectedApplicantObject> Objects { get; set; } = new System.Collections.ObjectModel.Collection<CollectedApplicantObject>();

        [Newtonsoft.Json.JsonProperty("tokenNonce", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string TokenNonce { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CollectedApplicantObject {
        [Newtonsoft.Json.JsonProperty("objectId", Required = Newtonsoft.Json.Required.Always)]
        public long ObjectId { get; set; }

        [Newtonsoft.Json.JsonProperty("objectType", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public ObjectsType ObjectType { get; set; }

        [Newtonsoft.Json.JsonProperty("objectName", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ObjectName { get; set; }

        [Newtonsoft.Json.JsonProperty("objectStatus", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string ObjectStatus { get; set; }

        [Newtonsoft.Json.JsonProperty("tanks", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<CollectedApplicantTankData> Tanks { get; set; } = new System.Collections.ObjectModel.Collection<CollectedApplicantTankData>();

        [Newtonsoft.Json.JsonProperty("devices", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<CollectedApplicantDeviceData> Devices { get; set; } = new System.Collections.ObjectModel.Collection<CollectedApplicantDeviceData>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CollectedApplicantTankData {
        [Newtonsoft.Json.JsonProperty("objectId", Required = Newtonsoft.Json.Required.Always)]
        public long ObjectId { get; set; }

        [Newtonsoft.Json.JsonProperty("tankId", Required = Newtonsoft.Json.Required.Always)]
        public long TankId { get; set; }

        [Newtonsoft.Json.JsonProperty("tankName", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string TankName { get; set; }

        [Newtonsoft.Json.JsonProperty("tankStatus", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string TankStatus { get; set; }

        [Newtonsoft.Json.JsonProperty("tankApiStatus", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string TankApiStatus { get; set; }

        [Newtonsoft.Json.JsonProperty("tankVolume", Required = Newtonsoft.Json.Required.Always)]
        public decimal TankVolume { get; set; }

        [Newtonsoft.Json.JsonProperty("tankCurrentVolume", Required = Newtonsoft.Json.Required.Always)]
        public decimal TankCurrentVolume { get; set; }

        [Newtonsoft.Json.JsonProperty("lastConnectionTime", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.DateTime? LastConnectionTime { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class CollectedApplicantDeviceData {
        [Newtonsoft.Json.JsonProperty("deviceId", Required = Newtonsoft.Json.Required.Always)]
        public long DeviceId { get; set; }

        [Newtonsoft.Json.JsonProperty("deviceName", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DeviceName { get; set; }

        [Newtonsoft.Json.JsonProperty("deviceType", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public DeviceType DeviceType { get; set; }

        [Newtonsoft.Json.JsonProperty("deviceStatus", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string DeviceStatus { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetPackageStatusResponseBody : ResponseBodyBase {
        [Newtonsoft.Json.JsonProperty("packageProcessingStatus", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public PackageProcessingStatus? PackageProcessingStatus { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum PackageProcessingStatus {

        [System.Runtime.Serialization.EnumMember(Value = @"Pending")]
        Pending = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Error")]
        Error = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"Success")]
        Success = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"Deleted")]
        Deleted = 3,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetPackagesStatusResponseBody : ResponseBodyBase {
        [Newtonsoft.Json.JsonProperty("result", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public System.Collections.Generic.ICollection<PackageIdWithStatus> Result { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PackageIdWithStatus {
        [Newtonsoft.Json.JsonProperty("packageId", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public string PackageId { get; set; }

        [Newtonsoft.Json.JsonProperty("packageProcessingStatus", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public PackageProcessingStatus PackageProcessingStatus { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class PackagesRequestBody : RequestBodyBase {
        [Newtonsoft.Json.JsonProperty("packageIds", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<string> PackageIds { get; set; } = new System.Collections.ObjectModel.Collection<string>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class RefItem {
        [Newtonsoft.Json.JsonProperty("code", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Code { get; set; }

        [Newtonsoft.Json.JsonProperty("text", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public string Text { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SendTankIndicatorsRequestBody : PackageRequestBody {
        [Newtonsoft.Json.JsonProperty("tanksMeasurements", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.ICollection<TankMeasurements> TanksMeasurements { get; set; } = new System.Collections.ObjectModel.Collection<TankMeasurements>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TankMeasurements {
        [Newtonsoft.Json.JsonProperty("tankId", Required = Newtonsoft.Json.Required.Always)]
        public long TankId { get; set; }

        [Newtonsoft.Json.JsonProperty("measurements", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<TankMeasurementData> Measurements { get; set; } = new System.Collections.ObjectModel.Collection<TankMeasurementData>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TankMeasurementData {
        [Newtonsoft.Json.JsonProperty("measurementDate", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTime MeasurementDate { get; set; }

        [Newtonsoft.Json.JsonProperty("mass", Required = Newtonsoft.Json.Required.Always)]
        public decimal Mass { get; set; }

        [Newtonsoft.Json.JsonProperty("massUnitType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public MassUnitType? MassUnitType { get; set; }

        [Newtonsoft.Json.JsonProperty("volume", Required = Newtonsoft.Json.Required.Always)]
        public decimal Volume { get; set; }

        [Newtonsoft.Json.JsonProperty("volumeUnitType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public VolumeUnitType? VolumeUnitType { get; set; }

        [Newtonsoft.Json.JsonProperty("level", Required = Newtonsoft.Json.Required.Always)]
        public decimal Level { get; set; }

        [Newtonsoft.Json.JsonProperty("levelUnitType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public LevelUnitType? LevelUnitType { get; set; }

        [Newtonsoft.Json.JsonProperty("density", Required = Newtonsoft.Json.Required.Always)]
        public decimal Density { get; set; }

        [Newtonsoft.Json.JsonProperty("temperature", Required = Newtonsoft.Json.Required.Always)]
        public decimal Temperature { get; set; }

        [Newtonsoft.Json.JsonProperty("oilProductType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public OilProductType? OilProductType { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum LevelUnitType {

        [System.Runtime.Serialization.EnumMember(Value = @"Millimeter")]
        Millimeter = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Centimeter")]
        Centimeter = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"Meter")]
        Meter = 2,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class SendTankTransfersRequestBody : PackageRequestBody {
        [Newtonsoft.Json.JsonProperty("tanksTransfers", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        [System.ComponentModel.DataAnnotations.MinLength(1)]
        public System.Collections.Generic.ICollection<TankTransfers> TanksTransfers { get; set; } = new System.Collections.ObjectModel.Collection<TankTransfers>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TankTransfers {
        [Newtonsoft.Json.JsonProperty("tankId", Required = Newtonsoft.Json.Required.Always)]
        public long TankId { get; set; }

        [Newtonsoft.Json.JsonProperty("transfers", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required]
        public System.Collections.Generic.ICollection<TankTransferData> Transfers { get; set; } = new System.Collections.ObjectModel.Collection<TankTransferData>();

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class TankTransferData {
        [Newtonsoft.Json.JsonProperty("startDate", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTime StartDate { get; set; }

        [Newtonsoft.Json.JsonProperty("endDate", Required = Newtonsoft.Json.Required.Always)]
        [System.ComponentModel.DataAnnotations.Required(AllowEmptyStrings = true)]
        public System.DateTime EndDate { get; set; }

        [Newtonsoft.Json.JsonProperty("levelStart", Required = Newtonsoft.Json.Required.Always)]
        public decimal LevelStart { get; set; }

        [Newtonsoft.Json.JsonProperty("levelEnd", Required = Newtonsoft.Json.Required.Always)]
        public decimal LevelEnd { get; set; }

        [Newtonsoft.Json.JsonProperty("levelUnitType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public LevelUnitType? LevelUnitType { get; set; }

        [Newtonsoft.Json.JsonProperty("massStart", Required = Newtonsoft.Json.Required.Always)]
        public decimal MassStart { get; set; }

        [Newtonsoft.Json.JsonProperty("massEnd", Required = Newtonsoft.Json.Required.Always)]
        public decimal MassEnd { get; set; }

        [Newtonsoft.Json.JsonProperty("massUnitType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public MassUnitType? MassUnitType { get; set; }

        [Newtonsoft.Json.JsonProperty("volumeStart", Required = Newtonsoft.Json.Required.Always)]
        public decimal VolumeStart { get; set; }

        [Newtonsoft.Json.JsonProperty("volumeEnd", Required = Newtonsoft.Json.Required.Always)]
        public decimal VolumeEnd { get; set; }

        [Newtonsoft.Json.JsonProperty("volumeUnitType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public VolumeUnitType? VolumeUnitType { get; set; }

        [Newtonsoft.Json.JsonProperty("operationType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public TransferOperationType? OperationType { get; set; }

        [Newtonsoft.Json.JsonProperty("oilProductType", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public OilProductType? OilProductType { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum TransferOperationType {

        [System.Runtime.Serialization.EnumMember(Value = @"Income")]
        Income = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"Outcome")]
        Outcome = 1,

    }



    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException : System.Exception {
        public int StatusCode { get; private set; }

        public string Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException) {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString() {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.18.2.0 (NJsonSchema v10.8.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class ApiException<TResult> : ApiException {
        public TResult Result { get; private set; }

        public ApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception innerException)
            : base(message, statusCode, response, headers, innerException) {
            Result = result;
        }
    }

}

#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore 472
#pragma warning restore 114
#pragma warning restore 108
#pragma warning restore 3016
#pragma warning restore 8603